SELECT 1;
-- CREATE TABLE IF NOT EXISTS Courses (
--     "course_id"                       VARCHAR(255) PRIMARY KEY,
--     "course_code"                     VARCHAR(8)   NOT NULL,
--     "year"                            INT          NOT NULL,
--     "course_name"                     VARCHAR(255) NOT NULL,
--     "uoc"                             INT          NOT NULL,
--     "faculty"                         VARCHAR(255),
--     "school"                          VARCHAR(255),
--     "campus"                          VARCHAR(255),
--     "career"                          VARCHAR(255) NOT NULL,
--     "terms"                           VARCHAR(255)[],
--     "modes"                           VARCHAR(255)[]
-- );