DROP TABLE IF EXISTS Enrolments CASCADE;

DROP TABLE IF EXISTS Times CASCADE;

DROP TABLE IF EXISTS Classes CASCADE;

DROP TABLE IF EXISTS Courses CASCADE;

DROP TYPE IF EXISTS career_enum CASCADE;
DROP TYPE IF EXISTS term_enum CASCADE;
DROP TYPE IF EXISTS status_enum CASCADE;
