name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Format
        run: cargo fmt --check

      - name: Build
        run: cargo build --verbose --locked

      - name: Lint
        run: cargo clippy --all-targets --all-features

      - name: Test
        run: cargo test --verbose --locked
