name: Cargo Build & Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt

  hourly_run:
    name: Run Cargo Command Hourly
    runs-on: ubuntu-latest
    schedule:
      - cron: '0 * * * *'  # Runs every hour
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo run --scrape --release
